### ISSUE TITLE
How to setup controllers with different multer upload configurations?

### ISSUE THREAD

**Issue by thurt** [byu-oit/openapi-enforcer-multer#1]
I am used to using multer middleware directly on a controller function, like

```js
const uploadImage = [uploadDisk.single("image"), (req, res, next) => { ... }]
const uploadProfilePicture = [uploadMemory.single("profile-picture"), (req, res, next) => { ... }]
```
this allows me to have a unique upload configured for each controller, for example, some controller endpoints have custom field names, file size limits, or use memory storage vs file storage.

however, with `openapi-enforcer-multer` i'm not quite sure how to do this or if its possible.

currently, I can only supply one multer instance to the `enforcerMulter` middleware. I have discovered that this must be installed before the `enforcer.middleware()` (otherwise i get validation errors), so i'm not able to get fine grain control on a per-controller basis.

```js
const uploadMemory = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 200000 }
});

// how do i use this one also?
const uploadDisk = multer({
  storage: multer.diskStorage({ destination: "./public/uploads" }),
  limits: { fileSize: 500000 }
});

app.use(enforcerMulter(enforcer, uploadMemory), enforcer.middleware())
```

**Comment by Gi60s** [comment]
Sorry for the slow response. I've been out of town for a week and without internet. I'll take a look at this today.

**Comment by Gi60s** [comment]
I've begun to write tests for this library (I know, bad practice to write tests later, sorry all) so that we can address these scenarios.

One question: what do you mean by `custom field names`?  Wouldn't those just be the names that you specify in your Open API document?

**Comment by thurt** [comment]
> One question: what do you mean by custom field names? Wouldn't those just be the names that you specify in your Open API document?

yes. i think you're right that's not an issue. its an issue if I want different file size limits or memory vs disk storage

**Comment by Gi60s** [comment]
I have a working solution on NPM in version `0.1.0`.

Check out the docs at https://byu-oit.github.io/openapi-enforcer-multer/multiple
