### ISSUE TITLE
Optional req.files for endpoints that consumes one of two types

### ISSUE THREAD

**Issue by jy95** [byu-oit/openapi-enforcer-multer#3]
Hello,

First, thank you for this cleary good documented module.
I have a issue with this module for an [endpoint](https://github.com/SourceCodeOER/sourcecode_api/blob/temp-master/openapi/paths/bulk.yaml#L115) that consumes either `application/json` or `multipart/form-data` ( depending of the context ).

When I tried to use the `application/json` version, I got a error because of this (`req.files` is undefined for JSON endpoint) : 

![image](https://user-images.githubusercontent.com/9306961/71312771-5f59b980-242f-11ea-86ec-503d4ef035a8.png)

Could you accept my PR (that should handle all the cases) ?
With this small modification, there will be no problem for people in my situation that cannot split an endpoint in two ^^

Thanks

**Comment by Gi60s** [comment]
Thanks for the PR. I've merged and published to NPM as version `0.1.2`.
