### ISSUE TITLE
TypeError: Cannot read property 'operation' of undefined

### ISSUE THREAD

**Issue by jy95** [byu-oit/openapi-enforcer-multer#7]
Hello,

I think you must add an check at [line 54](https://github.com/byu-oit/openapi-enforcer-multer/blob/master/index.js#L54) to prevent a bug with not existent path.

Here is what happens when an user tries to access an endpoint not on the API : 

```
  sourcecode_api:error_handler TypeError: Cannot read property 'operation' of undefined
  sourcecode_api:error_handler     at promise.then.openapi (D:\workspaceshit\exercises_library\node_modules\openapi-enforcer-multer\index.js:54:32)
  sourcecode_api:error_handler     at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
```

**Comment by Gi60s** [comment]
Nice! Thanks for the bug report.

I added a fix that is published to NPM as version `0.1.6`. If the path is not located in your OpenAPI document it will now pass the request to the next middleware.
